### ISSUE TITLE
404 error when validating schemas

### ISSUE THREAD

**Issue by osfrance** [FIWARE/data-models#137]
Hi, 
When I try to validate : 
  https://raw.githubusercontent.com/Fiware/dataModels/master/Weather/WeatherObserved/schema.json 
with data : 
  https://raw.githubusercontent.com/Fiware/dataModels/master/Weather/WeatherObserved/example.json 
I had an 404 error in : 
  https://fiware.github.io/dataModels/common-schema.json#/definitions/Location-Commons 
in Line 46 : 
  "location": { "$ref": "http://json-schema.org/geojson/geometry.json#" }, 
the url **http://json-schema.org/geojson/geometry.json** not exist !

Thanks for Help,
regards,

**Comment by jmcanterafonseca** [comment]
you need to have the geometry.json file locally

**Comment by ilarimikkonen** [comment]
@jmcanterafonseca I noticed the same. Could you please explain how this is supposed to work? How can we serve the file local, if it has an url assigned as reference?

**Comment by fgalan** [comment]
@ilarimikkonen I have the same problem (see https://github.com/FIWARE/dataModels/pull/373#issuecomment-479969230)

**Comment by jmcanterafonseca** [comment]
see 
https://github.com/FIWARE/dataModels/pull/373#issuecomment-480210961 

@ilarimikkonen that's easy it is served locally because the id is the same ...

**Comment by albertoabellagarcia** [comment]
1) thanks for the comments
2) This repo is currently frozen and no longer evolution will be held there. Currently, we deal with it here  https://github.com/smart-data-models 
3) now it validates 
https://raw.githubusercontent.com/smart-data-models/dataModel.Weather/master/WeatherObserved/example.json
against the schema
https://raw.githubusercontent.com/smart-data-models/dataModel.Weather/master/WeatherObserved/schema.json
If there is anything else please reopen this issue
Thanks
