### ISSUE TITLE
script to generate DataModel and SubDataModel skeletons

### ISSUE THREAD

**Issue by chicco785** [FIWARE/data-models#165]
in @smartsdk we have been discussing that such a script could be useful to simplify the creation of validated data models. feelings? would it be worth to spend time on it and including it here?

**Comment by jmcanterafonseca** [comment]
yup but I think first priority would be to finish the validation pull request

thanks!

**Comment by jmcanterafonseca** [comment]
this issue is related to #550

**Comment by albertoabellagarcia** [comment]
In the process to redesign the documentation process in order to make it more flexible, simple and subject to be automated.
