### ISSUE TITLE
About contributing Japanese documents

### ISSUE THREAD

**Issue by fisuda** [FIWARE/data-models#305]
Hi @jmcanterafonseca

I have translated .md files in this repository into Japanese.
Before sending a PR, may I ask something?

* May I put Japanese document in this repository?

* Where folder should the files be put?
My proposal is to put the Japanese .md files into `specs.ja`. The Japanese .md file except in spec folder renames as `.ja.md` and the `.ja.md` file is put in the same folder as the English .md file.

e.g.

* specs
    * Alert
        * doc
            * spec.md
    * README.md
* **specs.ja**  (including only .md files)
    * Alert
        * doc
            * spec.md
    * README.md
* validator
    * README.md
    * **README.ja.md**
* README.md
* **README.ja.md**

**Comment by jmcanterafonseca** [comment]
specs.ja (including only .md files)
   Alert
   doc
   spec.md ?? shoudn't this be spec.ja.md ? 


@jason-fox what do you think about this proposal?

**Comment by jason-fox** [comment]
Do we want to do this properly? **Read-the-docs/mkdocs** generated from markdown does not to a good job of internationalization. It is painful.

If we add  Japanese in the existing project then either it isn't rendered or both versions are rendered in one document, I mean we could display both English and Japanese docs  together in one project - but who (apart from @fisuda)  is fluent in both English and Japanese and wants them both in one document? However even then the Read-the-docs config  assumes by default that the only language is `en`.

It would be better to split up the existing project into three repos:

* DataModels `en` - A read-the-docs project for the English translation 
* DataModels `jp` - A read-the-docs project for the Japanese translation
* DataModels "common" - The validator, the JSON files and so on

The "common" repo could be set up as a submodule to share the JSON files.

There would need to be two separate projects on read-the-docs, they could then refer to each other as a  translation.

As a first step creating a `specs.ja` folder would be a good start though.

**Comment by jmcanterafonseca** [comment]
@jason-fox I'm not in favour of adding complexity to the dataModel Repo and would prefer to keep just the Repo we have. I don't believe we need to generate the Readthedocs in Japanese, but just add a link somewhere to the .md files translated to Japanese. 

So I prefer to create the specs.ja folder and put the content there. The question is should `spec.md` for the  Japanese be `spec.md` or `spec.md.ja.  I think the former would be clearer, even if these files are in a separated folder, the Japanese one.

**Comment by fgalan** [comment]
Based on how documenation translation is being implemented in fiware-orion repository maybe is better to use in filenames/directories:

.ja -> .jp

My two cents... :)

**Comment by fisuda** [comment]
@fgalan,
Thank you for your advice. 

My proposal is same as fiware-orion repo. The language code is `ja`, which is different from fiware-orion repo.This is according to [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1). In case of fiware-orion repo, I proposed same one. But, as `jp` had been already used, I used `jp` instead of `ja`.

**Comment by fisuda** [comment]
@jmcanterafonseca , @jason-fox 
> The question is should `spec.md` for the Japanese be `spec.md` or `spec.md.ja`.

In case of `spec.md.ja`, a file is not printed as markdown on github.
So, a file name should be `spec.md` or `spec.ja.md`.
I think that `spec.md` is better to avoid redundancy of `ja`.

**Comment by jmcanterafonseca** [comment]
@fisuda can we just have a new folder named

`specs.ja` which will contain all the specs following a similar structure than the `specs` folder? 

and within that folder the translations to the Japanese under `spec.ja.md`, for instance:

`specs.ja/Environment/AirQualityObserved/doc/spec.ja.md` 

and so on so forth.

**Comment by fgalan** [comment]
I don't have any strong opinion regarding a particular structure versus others. As far as there is some consistent structure, is fine.

With regards to acronym, I think the same should be used among all repos. Orion is currently using `jp` so I suggest to use `jp` also here or change Orion to use `ja`, whatever you prefer.

**Comment by jason-fox** [comment]
`ja` is the correct ISO 639-1 **Language** Code - Orion is incorrect.

`jp` is the ISO country code for Japan rather than the Japanese Language.

**Comment by albertoabellagarcia** [comment]
Currently reviewing the method to generate a multilanguage documentation.

**Comment by fisuda** [comment]
@albertoabellagarcia I understand. I close this issue.
