### ISSUE TITLE
Vehicle model not supported by Orion

### ISSUE THREAD

**Issue by jlanza** [FIWARE/data-models#324]
Vehicle model defines two locations: Location and PreviousLocation. Both of them should be defined using geo:json.

However, when pushing data to Orion you get the following error:
"You cannot use more than one geo location attribute when creating an entity [see Orion user manual]"

Therefore the solution I've found is remove the type from PreviousLocation and consider it is inferred from the Location.

You should update either Orion or the datamodel in order to avoid misunderstandings.

**Comment by fgalan** [comment]
This behaviour is documented for Orion. Please have a look at https://fiware-orion.readthedocs.io/en/master/user/ngsiv2_implementation_notes/index.html#limit-to-attributes-for-entity-location

**Comment by jmcanterafonseca** [comment]
closing this. Please open an issue in the corresponding Project.

**Comment by fgalan** [comment]
> closing this. Please open an issue in the corresponding Project.

It depens. If the outcome of this issue is to modify the Vehicle datamodel, then I think it is well placed in this repository.

**Comment by fgalan** [comment]
> do we need previous location in the datamodel? shouldn't be possible to get it from historical data?

Very good point. Because if the door is open for a PreviousLocation, why don't a PreviousPreviousLocation? And why don't a PreviousPreviousPreviousLocation? ;)

Context based models work better when the model is focused on current-state information (that's actually the real meaning for *context*). For past data (as a past location) historical data (persisted through Cygnus) should be used.

**Comment by jlanza** [comment]
PreviousLocation can be used to infer the heading direction and speed which are only mandatory if the vehicle is tracked. If the data provider is not giving that, then you can use Location and PreviousLocation to get this values. 
It is up to you, but I also consider that the restriction in Orion is something strange.
The other option could be that Location can be set as a Polyline, so the user can set as many coordinates as desired. But this is gonna give too much freedom, and I think the model should be clear and simple.

**Comment by fgalan** [comment]
> PreviousLocation can be used to infer the heading direction and speed which are only mandatory if the vehicle is tracked

Could that use case be achieved using historical context data (for instance, provided by a query to the STH API to location attribute)?

**Comment by chicco785** [comment]
This is something related to a discussion we are having for QuantumLeap. The discussion being that it would be nice to have, beside “real” entities also “virtual” entities computed as views over real entities. Some concept could apply somehow to attributes.

This would avoid having to compute “pieces” of the context via external data processing.

Anyhow I wonder if the “heading” is not an information supposed to be part of the context already.

iFede - Fede's mobile edition

**Comment by jmcanterafonseca** [comment]
just to clarify that not necessarily Data Models should be constrained to Orion limitations. Data Models are intended to be independent of the NGSI implementation, although generally they work with the Orion implementation. 

Wrt `previousLocation` I think it is a good idea as a very convenient way to infer heading, distance, speed, without having to inspect history. So -1 to remove it.

**Comment by chicco785** [comment]
you have `heading` and `speed` in the data model. to me `previousLocation` is redundant.

**Comment by albertoabellagarcia** [comment]
If there is a use case for this property, please reopen the issue, otherwise remain closed.
