### ISSUE TITLE
Versioning data models

### ISSUE THREAD

**Issue by minimalisti** [FIWARE/data-models#469]
Currently FIWARE data models do not have versioning information. We at CityIoT project have found that it would be useful to have this information in the data, or linked with it. Indicating what version of the data model was used would easy the development of applications using the data.

Some hinitial thoughts about how this versioning could be implemented:
- own versioning information could be added to a data model:
     - attribute (e.g. "version: { type: Number }")
     - metadata (e.g. added as metadata for the "id")
- version could indicated as an integer (should be sufficient), or using numbering schema like major.minor.revision

I am interested in finding out if others this versioning data would be useful, and would like to participate in developing this idea further.

**Comment by jmcanterafonseca** [comment]
current idea is to have just a pointer to the schema used to represent an Entity

```
{
  "id": "urn:ngsi-ld:X:1234",
  "type": "X",
  "attr1": {
   "value": "y"
  },
  "schema": "http://myschema.com/v1"
}
```

**Comment by minimalisti** [comment]
@jmcanterafonseca : very happy to hear that versioning has already been thought about! :+1: 

It seems to me that current FIWARE data models in this repo do not have a 'schema' attribute. Is it suggested to add this attribute to data models in use now? 

Or do you mean that versioning will be introduced with NGSI-LD? Schemas included in the @context-attribute seem to have (optional?) versioning in the URLs according to:
https://fiware-datamodels.readthedocs.io/en/latest/ngsi-ld_howto/index.html

**Comment by jmcanterafonseca** [comment]
yes, idea is to eventually add the `schema` attribute to the Data Models and to support it natively in NGSI-LD. In the meantime, I believe you can use it as a versioning mechanism in your application.

**Comment by minimalisti** [comment]
There is a obvious problem with everyone now using FIWARE data models adopting their own versioning schemes and version numbering before something official appears. In my view the tags used to indicate versions across all systems using FIWARE data models must be the same, so that application development is feasible, as for example WeatherObserved version 3 would mean that certain attributes are in the entities.  

If data model versioning would be different in each running system, the benefits it provides are diminished. Creating local versions of each data model should of course be possible, but there should be recommendations about how they should be tagged.

Any estimate on when is there going to some official versioning scheme in place with FIWARE data models? A roadmap is mentioned in this repo's documentation, but I could not find one.

**Comment by jmcanterafonseca** [comment]
we will recommend something once it is agreed at ETSI level, but, as I said, chances for the `schema` attribute are very high.

**Comment by jmcanterafonseca** [comment]
see PR #549

**Comment by jmcanterafonseca** [comment]
fixed https://github.com/FIWARE/data-models/blob/master/specs/guidelines.md#versioning
