### ISSUE TITLE
Ensure we always point to streams.lab in README's

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#476]
There are some READMEs where we still point to all, non-working endpoints. We need to fix that to point to streams.lab 

Example

https://github.com/FIWARE/dataModels/tree/master/specs/Environment/AirQualityObserved

we are pointing to 

curl -S -H 'fiware-service:airquality' -H 'fiware-servicepath:/Spain_Madrid' -H 'x-auth-token:<my_token>' "http://130.206.118.244:1027/v2/entities?options=keyValues&q=dateObserved:2016-11-28T12:00;stationCode:'28079004'"

which does not exist ...

**Comment by caa06d9c** [comment]
The same situation as in https://github.com/FIWARE/dataModels/issues/477

It's better to split into several steps:
- change already refactored harvesters and change available links
- refactor other harvesters
- change other links.

**Comment by jmcanterafonseca** [comment]
closing
