### ISSUE TITLE
get rid of fiware-service-path in public instance

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#477]
As we no longer want to promote the usage of FIWARE Service Path, let's get rid of it from the public instances (so the harvesters should not use the fiware-service-path) 

Note: This does not mean that we should change harvesters. Just configure them for not using service-path

**Comment by caa06d9c** [comment]
- weather-{forecast, observed, stations} - needs to be changed (they do not support empty service-path). 
- airquality-madrid, bicycle_hire_station_barcelona, import_pois_tourspain.py  - needs to be changed too, but refactored too, to be aligned with weather-* ones.
- airquality-barcelona not working at all, broken upstream.

so I think it's better to split this issue to 3 steps.
- change weather-*  - (it's easy to do)
- fix available links in docs
- refactor others
- fix other links.

**Comment by jaimeventura** [comment]
What about "Fiware-service"?

**Comment by caa06d9c** [comment]
Exists, and in use at streams.lab.fiware.org

**Comment by caa06d9c** [comment]
- [x] weather-forecast (Spain and Portugal )
- [x] weather-observed (Spain and Portugal)
- [x] weather stations (Spain)
- [ ] airquality (Madrid)
- [ ] airquality stations (Madrid)
- [ ] airquality (Barcelona)
- [ ] bicycle_hire_station_barcelona
- [ ] import_pois_tourspain

**Comment by albertoabellagarcia** [comment]
these services are no longer working however It is considered their reactivation.

**Comment by flopezag** [comment]
airquality (Madrid) is recovered and resolved some open issues on it. Need to analyse the rest of issues

**Comment by albertoabellagarcia** [comment]
Harvesting services should be done in a specific repo. This is not longer active
