### ISSUE TITLE
in harvesters and examples normalize DateTime always to UTC

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#483]

**Comment by jmcanterafonseca** [comment]
@caa06d9c can this be closed?

**Comment by albertoabellagarcia** [comment]
not further discussion for 6 months. close it.

**Comment by flopezag** [comment]
- [ ] weather-forecast (Spain and Portugal )
- [ ] weather-observed (Spain and Portugal)
- [ ] weather stations (Spain)
- [ ] weather stations (Portugal)
- [x] airquality (Madrid)
- [ ] airquality stations (Madrid)
- [ ] airquality (Barcelona)
- [ ] bicycle_hire_station_barcelona
- [ ] import_pois_tourspain
