### ISSUE TITLE
[Open311ServiceRequest] 'service_name' should not be part of this datamodel

### ISSUE THREAD

**Issue by jaimeventura** [FIWARE/data-models#510]
Datamodel Open311ServiceType represents a "service type" (a type of issue) and it has, amongs other, attributes "service_code" (a code that identifies a "service type", i.e. 1234) and a "service_name" with a string representation of that "service type"(i.e. "pothole on the street").
 
Open311ServiceRequest datamodel represents an issue (i.e 'my street has a big hole on the tar-mat '), which is from a specific "service type" (i.e.  1234 - "pothole on the street").

An entity of Open311ServiceRequest is linked to a Open311ServiceType, via  its attribute "service_type", but it has also a 'service_name'.
It doesn't make sense for Open311ServiceRequest to have this 'service_name', since this information is accessible via the linkage provided by the "service_code" to a Open311ServiceType.

In facto, according to the API documentation for open311'a GeoReport_v2,  when calling a "POST Service Request", 'service_name' is neither in the required parameters nor the optional ones.
So, i believe this should be removed.

**Comment by jason-fox** [comment]
Could you confirm version of the specification you are referring to? I assume you mean [http://wiki.open311.org/GeoReport_v2](http://wiki.open311.org/GeoReport_v2/#post-service-request)

Given that the specification is a living document, it is entirely possible that the requirement for including `service_name` has been removed at some point. In which case the FIWARE model will need to re-align.

**Comment by jaimeventura** [comment]
Thats correct.
I was specifically mentioning this[1].
One possible reason for the existence of the field in Open311ServiceRequest in the first place, is because the "Get Service Request" method[2] *does* include that field in the output.
But that doesn't mean it is included in its datamodel. As i previously mention, 'service_name' is neither in the required parameters nor the optional ones for the "POST Service Request", used to create the  Service Request.

If you're comfortable with this, i'll issue a pull request.
  
[1] http://wiki.open311.org/GeoReport_v2/#post-service-request
[2] http://wiki.open311.org/GeoReport_v2/#get-service-requests

**Comment by jmcanterafonseca** [comment]
@jaimeventura yes, please make a PR

**Comment by albertoabellagarcia** [comment]
move to this [repo][https://github.com/smart-data-models/dataModel.IssueTracking/tree/master)
