### ISSUE TITLE
[Open311ServiceType] rename 'open311:type' attribute to 'service_type' 

### ISSUE THREAD

**Issue by jaimeventura** [FIWARE/data-models#511]
Open311.org Service Type datamodel includes an attribute named "type" which, to avoid collision with the NGSI entity type, has been renamed to open311:type.

I would like to propose renaming it to "service_type" instead, to comply with the naming convention used (all lower-case, with underscore separating words aka. snake_case)

**Comment by jason-fox** [comment]
I'm not sure about that one, I think the name `open311:type` is an attempt at namespacing. I'm guessing the following NGSI-LD should be able to resolve to `http://example.com#type`

```json
{
    "id": "urn:ngsi-ld:Example:001",
    "type": "Example",
    "foo:type": {
        "type": "Property",
        "value": true
    },
   "@context": {
      "@vocab": "http://uri.etsi.org/ngsi-ld/",    
      "id": "@id",
      "type": "@type",
      "foo": "http://example.com#"
    }
}
```

This expansion looks syntactically valid to me, the problem is that I don't think this namespace expansion is supported yet, and could reduce the context broker throughput.

At the moment there is no real difference between having a renamed attribute called `open311:type` and one called `service_type` so  I wouldn't like to unilaterally update the attribute name without further discussion.

**Comment by jason-fox** [comment]
Requesting further input from @jmcanterafonseca @kzangeli @caa06d9c

**Comment by kzangeli** [comment]
First of all, the "builtins" of the API can never be overwritten, e.g. "id" and "type" for entities, "type" for attributes, etc. If we were to let users overwrite those, the the broker wouldn't work.

Once prefix expansion (issue https://github.com/FIWARE/context.Orion-LD/issues/73) is implemented in the broker, constructs like "foo:type" can be used.

However, there's an execution overhead with prefix expansion and this will make the broker less efficient.
I would not encourage its use, not if there is a good alternative by simply use xxx_type or something similar. I.e. include the prefix in the keys without using prefix expansion.

**Comment by jaimeventura** [comment]
Allow me to persist with my proposal with this extra reason: if open311 attribute 'type' was represented (renamed?) as 'open311:type', why not do the same for the other open311 attributes (service_code-> open311:service_code, service_name->open311:service_name, ...)?
I proposed a 'rename', but my ultimate motivation was to have a little more of coherence on the naming across all the ported attributes.

**Comment by kzangeli** [comment]
I agree, if "type" gets a prefix, then they should all have the same prefix.

However, would it be unthinkable to replace"type" with a synonym?
There are plenty ... "sort", "class", "category", "variety", "species", "family" ...

Of all these (and more), it is only "type" that you cannot use, as it is part of the API

**Comment by jason-fox** [comment]
Whenever there is a model clash with the default namespace I can see three options:

### Prefix the offending elements only  (e.g. `type`->`open311:type`)

-  *Pro:* Current model does this, maintains base attribute naming with Open311 spec
-  *Con:* Inconsistent shortnames

### Rename the offending elements only (e.g. `type`->`category`)

-  *Pro:* Human readable
-  *Con:* Need to find acceptable synonyms, lose 1-to-1 alignment of attribute names

### Prefix all the model elements (`open311:this`, `open311:that`)

- *Pro:* easily defined standard (but why only for some models)
- *Con:* More attributes are misaligned, requires prefix expansion issue to be implemented.

Whichever is chosen I'd like to ensure this gets applied **consistently** to all models.

**Comment by jmcanterafonseca** [comment]
I would go here for the simplest options and if service_type solves the issue, let's go for that.

However, we should do the same, for the sake of consistency, with other attributes that might be prefixed ...

**Comment by jason-fox** [comment]
After much discussion with @jmcanterafonseca I would like to propose the following:

- Rename `open311:type` to `open311Type`. (camelCasing)
- Update the open311ServiceType spec to clarify the relationship with open311.
- Update the guidelines to explain what to do in case of clashes with core  NGSI

### Reasoning

- we *absolutely* cannot clash with `type` - core context always wins.
- we already have `vehicleType`, `museumType` etc.
- all existing `xxxType` attributes are camel case (as indeed are the vast majority of all attributes)
- That colon `:` is just plain ugly any override can be done in `ldcontext_mappings.json`

**Comment by kzangeli** [comment]
Not using colon (:) has another important advantage - to avoid partial expansion which when used slows down the broker.

**Comment by albertoabellagarcia** [comment]
pending to be implemented

**Comment by albertoabellagarcia** [comment]
Implemented in the [smart data models initiative](https://github.com/smart-data-models/dataModel.IssueTracking/tree/master)
