### ISSUE TITLE
think about a property to convey what mission is delivering the vehicle

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#52]
y algo tipo "servicio" o misión o similar. La ruta, o si está atendiendo una llamada, una incidencia...algo que especifique una tarea concreta que tenga encomendada ese vehículo en ese momento

**Comment by jmcanterafonseca** [comment]
added the `serviceStatus` property, probably we are going to need more values in the enumeration. Leaving it open for now.

**Comment by albertoabellagarcia** [comment]
it would need to be reopened in case more status are required
