### ISSUE TITLE
In the Agri Data Models align Relationship names to be always verbs

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#528]
This implies changes also in the GSMA Repos.

**Comment by jmcanterafonseca** [comment]
@fdelavega what is the status of this?

**Comment by fdelavega** [comment]
The FIWARE part is ready and the PR to the GSMA is approved. Althought, we are waiting for response regarding the potential issue with the context

**Comment by jmcanterafonseca** [comment]
as the FIWARE part is fixed, closing this.
