### ISSUE TITLE
[Agri] Ensure documentation of extended Attributes (non present in GSMA) is added at least to JSON Schema

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#529]

**Comment by jmcanterafonseca** [comment]
@fdelavega what is the status of this?

**Comment by jmcanterafonseca** [comment]
to be solved together with #553

**Comment by albertoabellagarcia** [comment]
Now documentation is generated automatically for all the data models in the [smart data models](https://github.com/smart-data-models). Further info there.
