### ISSUE TITLE
[Agri] All the timestamp metadata in NGSIv2 examples is wrong

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#532]
The metadata type is missing ... and it should be "DateTime"  ...

**Comment by fdelavega** [comment]
Do you mean in DateTime attributes, right? Not createdAt and modifiedAt ones

**Comment by jmcanterafonseca** [comment]
it is in NGSI v2 metadata. You need to add "type": "DateTime"

thanks!

**Comment by fdelavega** [comment]
I think this one can be closed

**Comment by jmcanterafonseca** [comment]
@fdelavega can you reference the PR on which this was fixed?

**Comment by fdelavega** [comment]
is the #542
