### ISSUE TITLE
Reusing existing Linked Data vocabularies

### ISSUE THREAD

**Issue by pietercolpaert** [FIWARE/data-models#536]
I’ve noticed the work on a JSON API for GTFS data here: https://github.com/FIWARE/dataModels/blob/master/specs/UrbanMobility/GtfsTrip/doc/spec.md

It links to Linked GTFS, but as far as I can see, the Linked GTFS terms are not mentioned in the `@context`. Furthermore, a specific way of creating non HTTP identifiers is put forward, contrary to existing mapping scripts such as
 -  https://github.com/OpenTransport/gtfs-csv2rdf,
 - https://github.com/linkedconnections/gtfs2lc or
 -  https://github.com/oeg-upm/morph-csv/blob/master/evaluation/transport-performance/mappings/gtfs.yml

Does NGSI-LD always need its own NGSI-specific mappings?

**Comment by jmcanterafonseca** [comment]
yes, we need to Cross Reference Linked GTFS in the @context

**Comment by jmcanterafonseca** [comment]
regarding ids, please could you put an example of proper ids?

**Comment by jmcanterafonseca** [comment]
you can use any URI for identifying your Entities in NGSI-LD, so fine. 

Existing Linked Open Data vocabularies can be used by just defining the proper mappings in the @context. Our @context generation tool maps terms by default to a FIWARE URI but exceptions can be defined in the following file

https://github.com/FIWARE/dataModels/blob/master/tools/ldcontext_mappings.json 

So you can make a PR to define exceptions for GTFS terms and map them to the URIs already defined by the LinkedGTFS project

@pietercolpaert would you be in a position to make such a PR?

Thanks!

**Comment by pietercolpaert** [comment]
@jmcanterafonseca I tried to work on this, but immediately came in conflict with the data model here. Simple example: you use 0, 1 or 2 as values for wheelchair accessibility. Back in 2014 we chose to map this to URIs instead of literal values.

Are these data models still able to change?

**Comment by jmcanterafonseca** [comment]
sure, they are not written in stone. please propose alternative values for
that and we can fix it.

**Comment by pietercolpaert** [comment]
@jmcanterafonseca So, we had to wrap our heads fully around the spec to understand how we could do that. Sorry it took a while to respond.

We created a small example below. Can you validate this looks like something you would use?

We propose not to use the expanded form because with this example:
```json
{
  "id":"http://example.org/trips/Spain:Malaga:1",
  "type":"Trip",
  "direction":{
    "type":"Property",
    "value":false
  },
  "headsign":{
    "type":"Property",
    "value":"San Andr\u00e9s"
  },
  "hasRoute":{
    "type":"Relationship",
    "object":"http://example.org/routes/Spain:Malaga:1"
  },
  "hasService":{
    "type":"Relationship",
    "object":"http://example.org/services/Malaga_LAB"
  },
  "hasShape":{
    "type":"Relationship",
    "object":"http://example.org/shapes/Shape01"
  },
  "@context":[
    {
      "gtfs":"http://vocab.gtfs.org/terms#",
      "Trip":"gtfs:Trip",
      "direction":"gtfs:direction",
      "headsign":"gtfs:headsign",
      "hasRoute":"gtfs:route",
      "hasService":"gtfs:service",
      "hasShape":"gtfs:shape"
    },
    "https://cors-anywhere.herokuapp.com/https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
  ]
}
```
The range of  e.g., `gtfs:headsign` is not any longer an `xsd:string`. This break compliance with the vocabulary.

In the simplified form it does work however:
```json
{
  "id":"http://example.org/trips/Spain:Malaga:1",
  "type":"Trip",
  "direction":false,
  "headsign":"San Andr\u00e9s",
  "hasRoute":"http://example.org/routes/Spain:Malaga:1",
  "hasService":"http://example.org/services/Malaga_LAB",
  "hasShape":"http://example.org/shapes/Shape01",
  "@context":[
	{
  	"gtfs":"http://vocab.gtfs.org/terms#",
  	"Trip":"gtfs:Trip",
  	"direction":"gtfs:direction",
  	"headsign":"gtfs:headsign",
  	"hasRoute":"gtfs:route",
  	"hasService":"gtfs:service",
  	"hasShape":"gtfs:shape"
	},
	"https://cors-anywhere.herokuapp.com/https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
  ]
}
```

**Comment by jmcanterafonseca** [comment]
that can work but instead of putting the GTFS mappings inline in the
@context you can add those mappings to
https://github.com/FIWARE/data-models/blob/master/tools/ldcontext_mappings.json
so that when the FIWARE Data Models @context is automatically generated
mappings for GTFS are conveniently added. That way you could still be using
https://schema.lab.fiware.org/ld/context as your main @context

**Comment by albertoabellagarcia** [comment]
Hi Pieter it's me Alberto Abella.
could you move this issue to here
https://github.com/smart-data-models/dataModel.UrbanMobility
because these repos are frozen since February and evolution would be derived to there
