### ISSUE TITLE
[Roadmap] Generate FIWARE Data Models Schema in *JSON-LD* as it happens with schema.org

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#551]
See https://schema.org/version/3.9/schema.jsonld as a representation of the schema of Schema.org in JSON-LD. 

It would be good to do the same with the Schema of FIWARE Data Models as @jason-fox did within the Tutorials see https://github.com/FIWARE/tutorials.Relationships-Linked-Data#relationships-with-linked-data

It has to be decided what would be the source for generating such schema in JSON-LD. One option is to use the current (annotated) JSON Schemas to do so. 

We should not forget to make the JSON-LD content generated ready for multi-language.

**Comment by albertoabellagarcia** [comment]
this is how it is going to be solved
