### ISSUE TITLE
[Roadmap] Full documentation of Smart Agri Data Models

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#553]
Currently in this Repository for Smart Agri there is only the schemas and examples, relying on the GSMA Github space for descriptions. However, new Attributes and Entities have been defined here. So we have here two options:

1. Align with GSMA and make PRs to GSMA's Repo
2. Develop the full documentation in this Repo. 

If we go for option 2, then the new documentation generation tool to be developed by issue #550 should be used

**Comment by albertoabellagarcia** [comment]
it will be checked 'soon' with an automatic tool to check that all properties defined in the schema, are defined in the spec and in the examples
