### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by urabe0225** [FIWARE/data-models#563]
the page isn’t working  http://www.who.int/uv/intersunprogramme/activities/uv_index/en/ 
in [specs/Weather/WeatherForecast/doc/spec.md](https://github.com/FIWARE/data-models/blob/master/specs/Weather/WeatherForecast/doc/spec.md)

**Comment by fgalan** [comment]
Sure? :) I have just clicked and my browsers shows:

![imagen](https://user-images.githubusercontent.com/1534240/70640430-3752a500-1c3c-11ea-8bc0-986b34958692.png)

**Comment by urabe0225** [comment]
I am sorry.
When I accessed it, it was dead page.
