### ISSUE TITLE
[WeatherObserved] windDirection attribute in Data model, schema doesn't match definition

### ISSUE THREAD

**Issue by Rui-Magalhaes-APD** [FIWARE/data-models#567]
The [definition](https://github.com/FIWARE/data-models/blob/master/specs/Weather/WeatherObserved/doc/spec.md) of the windDirection states: "The wind direction expressed in decimal degrees compared to geographic North (measured clockwise), encoded as a Number." This definition implies that North is the 0º and that would make the measure range between 0º and 360º. But the [json schema](https://github.com/FIWARE/data-models/blob/8f3cdfec7665bba5312ceab281433ab0709f1858/specs/Weather/weather-schema.json#L67) is coded to check for ranges between -180º and 180º. 

The suggestion would be to correct the json schema to check for the range [0º ; 360º[. In fact, this range is the most used. A lot of sites use this range (e.g. [windfinder.com](https://www.windfinder.com/forecast/lordelo_do_ouro)) and this range is also mentioned in literature about measuring, as shown in "Handbook of Measurement in Science and Engineering." by John Wiley & Sons.

This issue also applies to WeatherForecast

**Comment by albertoabellagarcia** [comment]
I am Alberto Abella, currently starting to curate data models. Rui, you are definitely right, and this change will be implemented as you suggest.

**Comment by Rui-Magalhaes-APD** [comment]
Thanks for the correction.
The Weather forecast, for the wind measurements, has the same source, so it should be corrected to.
I have seen the change on the json schema. But the example still has a negative value ("-45"). It should be changed too, to avoid confusion for others
