### ISSUE TITLE
[WeatherObserved] Creation of attribute uVIndex

### ISSUE THREAD

**Issue by Rui-Magalhaes-APD** [FIWARE/data-models#570]
I suggest the creation of the attribute uVIndex since there are weather observation devices that measure the UV index.

**Comment by jaimeventura** [comment]
Hey all,
any update on this?
I volunteer do work on this and issue a pull request,  if there an agreement in inclusion of such atribute in the datamodel.

**Comment by albertoabellagarcia** [comment]
move this issue to https://github.com/smart-data-models. please

**Comment by Rui-Magalhaes-APD** [comment]
I would gladly do it, but unfortunately I don't have permissions to do it. Can you do it or give permissions to do it?
Thank you.

**Comment by Rui-Magalhaes-APD** [comment]
Im closing this issue in favor of [this one](https://github.com/smart-data-models/dataModel.Weather/issues/5).
