### ISSUE TITLE
Error Json-Ld parse context 

### ISSUE THREAD

**Issue by superdell** [FIWARE/data-models#582]
Error Json-Ld parse context, not valid:
ccs/sae
bbox
biodieser ethanol
commercial supply
hybrid electric/diesel
hybrid electric/petrol
rainwater capture
snow/ice
water dam

Tested with https://json-ld.org/playground/ and https://github.com/filip26/titanium-json-ld

**Comment by Ciro99678** [comment]
Same error with this context : https://schema.lab.fiware.org/ld/context.jsonld

**Comment by albertoabellagarcia** [comment]
1) this repo is here only for historical reasons. Development is done [Smart data models initaitive](https://github.com/smart-data-models) and its [web page](https://smartdatamodels.org/) 
2) It's been fixed issues on these:  ccs/sae,  hybrid electric/diesel, hybrid electric/petrol, now/ice
could you move this issue to this [repo](https://github.com/smart-data-models/data-models) and provide further details?
