### ISSUE TITLE
[Vehicle] "heading" or "Azimuth"? Terminology review

### ISSUE THREAD

**Issue by LeonanCarvalho** [FIWARE/data-models#77]
> `heading` : Denotes the direction of travel of the vehicle and is specified in decimal degrees, where 0° ≤ heading < 360°, counting clockwise relative to the true north. If the vehicle is stationary (i.e. the value of the speed attribute is 0), then the value of the heading attribute must be equal to null. null MAY be used if heading is transiently unknown for some reason.

The value thats represent direction degrees relative to north is common called [azimuth](https://en.wikipedia.org/wiki/Azimuth), an azimuth is an angular measurement in a spherical coordinate system. 
Looking for a terminology, on VM9 models we use azimuth as terminology because this post: 

> A **heading** (in the general case of moving "forward") is the direction your nose(of a plane) is pointed in. This may not be your course ([as discussed here)](http://aviation.stackexchange.com/questions/8000/what-are-the-differences-between-bearing-vs-course-vs-direction-vs-heading-vs-tr).
> Headings are measured from onboard a traveling vehicle or object (e.g. from the cockpit of an aircraft or the bridge of a ship at sea).
> 
> An **azimuth** is a bearing, more precisely a compass bearing from a specific point of observation like a radar station. (The "North" used as a reference may be either magnetic or true depending on the system you're working with, but for purposes of this discussion it doesn't matter.)
> Often the point of observation is fixed (ground radar, a control tower, an artillery spotter, etc.), though it need not be as long as the observation can be mapped to a compass bearing somehow.

Source: http://aviation.stackexchange.com/questions/24899/what-is-the-difference-between-azimuth-and-heading

So, exists a [big difference](http://wikidiff.com/azimuth/heading) between heading and azimuth.

Almost all compass as the sensors will use a magnetic sensor (so will use magnetic north) to determine the Azimuth degrees or will [calculate based on 2 positions ](http://www.dcode.fr/azimuth). In all cases, the terminology used is Azimuth.

**Comment by albertoabellagarcia** [comment]
so, It is clear the difference between azimuth and heading. We have in the data model heading. Are you suggesting using also / replace with azimuth? 
Either case currently evolution of these data models are here. https://github.com/smart-data-models/dataModel.Transportation/blob/master/Vehicle/schema.json
please reopen this issue if necessary there https://github.com/smart-data-models/dataModel.Transportation/issues
