### ISSUE TITLE
For WeatherObserved include accumulated values on a daily basis

### ISSUE THREAD

**Issue by jmcanterafonseca** [FIWARE/data-models#88]
use this information as reference:

http://www.aemet.es/es/eltiempo/observacion/ultimosdatos/ayuda

**Comment by LeonanCarvalho** [comment]
Another format that I know (used here http://150.163.255.234/salvar/mapa_interativo/interativo/grafico_CEMADEN.php?idpcd=3276&uf=RJ#infopcds)
Include accumulated values of  1,6,12,24,72 and	96 hours

**Comment by albertoabellagarcia** [comment]
moved, if necessary to new repository https://github.com/smart-data-models/dataModel.Weather
